### ISSUE TITLE
scri.SpEC.read_metadata can't handle empty assignments, should get other updates in sxs.metadata

### ISSUE THREAD

**Issue by duetosymmetry** [moble/scri#11]
scri.SpEC.read_metadata will fail on metadata.txt files that contain empty assignments, e.g. `keywords = ` on a line by itself (which is extremely common). This method also does not use the try: ast.literal_eval approach which is in use in sxs.metadata .

**Comment by moble** [comment]
I didn't even realize that this code existed!  It looks like I wrote it before `sxs` even existed, and clearly isn't as good.  So I'm just going to remove this function in favor of `sxs`'s version.
