### ISSUE TITLE
Should sample_waveforms.py:modes_constructor be generalized so that storage destination can be passed?

### ISSUE THREAD

**Issue by duetosymmetry** [moble/scri#12]
Right now, [`sample_waveforms.py:modes_constructor`](https://github.com/moble/scri/blob/72aaa1aa8ea4a86b4435f2a6bcef95d02a31ac97/sample_waveforms.py#L13-L50) always allocates storage for a new `WaveformModes` object. A user may desire to set up storage in advance and have `modes_constructor` write into that storage, then create the `WaveformModes` object using that storage, to avoid allocation if it is not needed. However, this would require a change to the signature for `data_functor` so that it can accept the destination as well.

**Comment by moble** [comment]
I think it should work to just use a closure, as in
```python
def leo_waves(blablabla):
    storage = whatever_you_want
    def data_functor(t, LM):
        for i, m in enumerate(LM[:, 1]):
            storage[:, i] = i*m
        return storage
    return modes_constructor(blablabla, data_functor)
```
Since the closure is called before `leo_waves` exits, `storage` gets used before the return statement, so the magic of python reference counting should keep it alive inside the `WaveformModes` object returned by `modes_constructor`.

**Comment by duetosymmetry** [comment]
Very good point, I should have thought of that! Closing.
