### ISSUE TITLE
Spline argument bbox really doesn't do what you'd think

### ISSUE THREAD

**Issue by moble** [moble/scri#15]
Despite what any reasonable person would think from [the documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.InterpolatedUnivariateSpline.html) the `bbox` argument to `InterpolatedUnivariateSpline` actually [doesn't do](https://stackoverflow.com/a/45909136/1194883) what is needed here:

https://github.com/moble/scri/blob/1ed24d90737d1b9fd91be07223f02e744d9ecc32/waveform_modes.py#L403-L407

It sets the limits of the knots, or something like that.  In particular, the `bbox` limits actually have to be at or *outside* the limits of `times`, or you get an error.

The new `quaternion.definite_integral` function should actually handle this whole chunk correctly with something like

```python
    return definite_integral(integrand, times, t0, t1)
```

Note that [I added logic to the core function](https://github.com/moble/quaternion/blob/67fc7370a6679c2810875a173ad94aa0f6c403bc/calculus.py#L396) that just slices `integrand` and `times` to focus on the requested range of times — which I believe was the motivation for using `bbox` here (and could save time in some cases by not fitting a spline to unused data).  But because splines can have weird transients at the beginning and end, I included additional padding of up to 10 unused points on each side where possible, which should be overkill.

@duetosymmetry  I'm opening this just so I don't forget about it. That function from `quaternion` isn't fully deployed yet, but if you get a chance to try out my proposed fix, let me know how it goes.

**Comment by duetosymmetry** [comment]
Wow, that is some cryptically-written documentation! Nice catch.

FWIW, I think the largest number of padding points you'd ever need is given by half the polynomial order of the spline interpolant. But since it's a constant factor, it won't matter... unless somebody is using 20th order interpolation or higher, in which case the hardcoded 10 will be wrong.

**Comment by duetosymmetry** [comment]
Because of PR #14, I think this issue can be closed.
