### ISSUE TITLE
Save the COM correction parameters into m̶e̶t̶a̶d̶a̶t̶a̶ H5 attributes

### ISSUE THREAD

**Issue by duetosymmetry** [moble/scri#4]
We should save, into a metadata file,  the \alpha and \beta parameters that go into the COM correction.

**Comment by duetosymmetry** [comment]
I think we decided the COM correction parameters should go into the H5 files as attributes rather than into the metadata.

**Comment by moble** [comment]
Yeah, but I was thinking that I already make some additions when converting to metadata.json from metadata.txt.  So it wouldn't be hard to add a step where I check for the existence of H5 files with those attributes, and then just add them to metadata.json as extra top-level fields.

The problem with this is that it may not be completely reliable.  For example, after the JSON file is written, the H5 files may be change, and there would be no signal that the JSON file should be redone.
