### ISSUE TITLE
Improved documentation?

### ISSUE THREAD

**Issue by nilsdeppe** [moble/scri#47]
I'd like to use scri to extrapolate finite radii waveforms, but from the ReadTheDocs it's not clear how to actually do that with scri. It would be super useful if there were a set of tutorials or something to show how to use scri for such tasks.

**Comment by moble** [comment]
This seems to be [resolved to Dante's satisfaction now](https://scri.readthedocs.io/en/latest/tutorial_extrapolation.html).
