### ISSUE TITLE
Enhancement: Add BMS group multiplication calculations

### ISSUE THREAD

**Issue by duetosymmetry** [moble/scri#74]
@keefemitman and I worked out what to do (requires being able to conjugate a supertranslation ɑ(θ,ɸ) by a Lorentz boost; then everything else will follow easily). The question is whether there should be a new type `BMS` added. I think it's natural to add such a type. However, current code stores BMS transformations as dicts rather than an object of type `BMS`, so to make a uniform interface, several APIs may change. Requesting comment from @moble

**Comment by keefemitman** [comment]
I think it should suffice to just define a function which takes as inputs two dictionaries of BMS transformations and returns a single dictionary of BMS transformations. That way we can easily write this function now and make sure it works with the `transformation` function before making things more "formal".

**Comment by moble** [comment]
Yeah, I think using `dict`s as the actual data structure would be best for backwards compatibility.  That's not to say it wouldn't be fun to have actual classes implementing these properties underneath, but for the purposes of the user interface, inertia weighs heavily.

**Comment by keefemitman** [comment]
Can we close this? @duetosymmetry

**Comment by duetosymmetry** [comment]
Sure!
