### ISSUE TITLE
waveform_grid and asymptotic_bondi_data transform differently

### ISSUE THREAD

**Issue by keefemitman** [moble/scri#87]
It seems that when transformed via a supertranslation, `waveform_grid` and `asymptotic_bondi_data` objects transform somewhat differently. I haven't dug through the code, but it looks the relationship between the transformations that map to the same frame are \alpha(waveform_grid)=4\alpha(asymptotic_bondi_data). I assume this is due to a convention choice? E.g., using a NP definition instead of a GHP definition for \eth operators or something.

**Comment by moble** [comment]
Closed by 73fd2052299314de5b3dc3da11f605b2a51b9675, which appeared in https://github.com/moble/scri/releases/tag/v2022.8.6.  I also added a pretty thorough test [here](https://github.com/moble/scri/blob/3c00b920888f9ac802f3297a7fb3bc2a7249a5fd/tests/test_asymptoticbondidata.py#L165).

**Comment by keefemitman** [comment]
Nice! Thanks Mike!
